language: node_js
node_js:
    - '12.8.1'

branches:
    only:
        - master

before_script:
    - npm install -g firebase-tools

script:
    - npm run build
    - npm run test:unit

after_success:
    - firebase deply --token $FIREBASE_TOKEN

notifications:
    email:
        recipients:
            - f2hard3@gmail.com
        on_success: always
        on_failure: always
